// Before you start, make sure that the set color of the brush is gray (i.e. double click on the brush icon and set the color to gray). 
// To execute the script: Plugins > Macros > Run.. > find the script and run it.

input = "/Users/sarawestman/Desktop/Projekt/Larver/2022/Insect_experiment_2022/Analysis/Victor/Leaf_scans_Sara/";
output = "/Users/sarawestman/Desktop/Projekt/Larver/2022/Insect_experiment_2022/Analysis/test/res_sara/";


function leaf_pixel(input, output, filename) {
		open(input + filename);
		run("Set Scale...", "distance=1169.6438 known=9 unit=cm global");
		dotIndex = indexOf(filename, "." );
		filename_out = substring(filename, 0, dotIndex );
		run("Color Threshold...");
		// Color Thresholder 1.52q
		// Autogenerated macro, single images only!
		min=newArray(3);
		max=newArray(3);
		filter=newArray(3);
		a=getTitle();
		run("HSB Stack");
		run("Convert Stack to Images");
		selectWindow("Hue");
		rename("0");
		selectWindow("Saturation");
		rename("1");
		selectWindow("Brightness");
		rename("2");
		min[0]=0;
		max[0]=255;
		filter[0]="pass";
		min[1]=0;
		max[1]=255;
		filter[1]="pass";
		min[2]=156;
		max[2]=255;
		filter[2]="pass";
		for (i=0;i<3;i++){
		  selectWindow(""+i);
		  setThreshold(min[i], max[i]);
		  run("Convert to Mask");
		  if (filter[i]=="stop")  run("Invert");
		}
		imageCalculator("AND create", "0","1");
		imageCalculator("AND create", "Result of 0","2");
		for (i=0;i<3;i++){
		  selectWindow(""+i);
		  close();
		}

		selectWindow("Result of 0");
		close();
		selectWindow("Result of Result of 0");
		rename(a);
		
		// Colour Thresholding-------------
		//setThreshold(255, 255);
		setOption("BlackBackground", true);
		run("Make Binary");
		floodFill(44, 36);
		floodFill(2433, 42);
		floodFill(44, 3484);
		floodFill(2436, 3476);

		selectWindow(filename);
		run("8-bit");
		nBins = 256;
		getHistogram(value, count, nBins);
		run("Clear Results");
		for (i=0; i<nBins; i++){
		  	setResult("Value", i, value[i]);
		  	setResult("Count", i, count[i]);
			}

		updateResults();
		saveAs("Results",output+filename_out+".txt");
		saveAs("Tiff", output + filename_out);
		close();
}

list = getFileList(input);
for (i = 0; i < list.length; i++){
        leaf_pixel(input, output, list[i]);
}